import { Book } from "./types/book"

/**
 * Maps internal book names to API.Bible USFM book IDs
 * @see https://ubsicap.github.io/usfm/identification/books.html
 */
export const bookToApiBibleId: Record<Book, string> = {
    genesis: "GEN",
    exodus: "EXO",
    leviticus: "LEV",
    numbers: "NUM",
    deuteronomy: "DEU",
    joshua: "JOS",
    judges: "JDG",
    ruth: "RUT",
    "1_samuel": "1SA",
    "2_samuel": "2SA",
    "1_kings": "1KI",
    "2_kings": "2KI",
    "1_chronicles": "1CH",
    "2_chronicles": "2CH",
    ezra: "EZR",
    nehemiah: "NEH",
    esther: "EST",
    job: "JOB",
    psalm: "PSA",
    proverbs: "PRO",
    ecclesiastes: "ECC",
    song_of_solomon: "SNG",
    isaiah: "ISA",
    jeremiah: "JER",
    lamentations: "LAM",
    ezekiel: "EZK",
    daniel: "DAN",
    hosea: "HOS",
    joel: "JOL",
    amos: "AMO",
    obadiah: "OBA",
    jonah: "JON",
    micah: "MIC",
    nahum: "NAM",
    habakkuk: "HAB",
    zephaniah: "ZEP",
    haggai: "HAG",
    zechariah: "ZEC",
    malachi: "MAL",
    matthew: "MAT",
    mark: "MRK",
    luke: "LUK",
    john: "JHN",
    acts: "ACT",
    romans: "ROM",
    "1_corinthians": "1CO",
    "2_corinthians": "2CO",
    galatians: "GAL",
    ephesians: "EPH",
    philippians: "PHP",
    colossians: "COL",
    "1_thessalonians": "1TH",
    "2_thessalonians": "2TH",
    "1_timothy": "1TI",
    "2_timothy": "2TI",
    titus: "TIT",
    philemon: "PHM",
    hebrews: "HEB",
    james: "JAS",
    "1_peter": "1PE",
    "2_peter": "2PE",
    "1_john": "1JN",
    "2_john": "2JN",
    "3_john": "3JN",
    jude: "JUD",
    revelation: "REV",
}

/**
 * Reverse mapping from API.Bible book ID to internal book name
 */
export const apiBibleIdToBook: Record<string, Book> = Object.fromEntries(
    Object.entries(bookToApiBibleId).map(([book, id]) => [id, book as Book]),
) as Record<string, Book>
