import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import { useEffect, useState } from 'react'

import { Arena } from '~/components/arena'
import { api } from '~/utils/api'

export function useDebounce<T>(value: T, delay: number): T {
    const [debouncedValue, setDebouncedValue] = useState(value)

    useEffect(() => {
        const handler = setTimeout(() => {
            setDebouncedValue(value)
        }, delay)

        return () => {
            clearTimeout(handler)
        }
    }, [value, delay])

    return debouncedValue
}

export default function Home() {
    const [value, setValue] = useState('Psalm 1')
    const debouncedValue = useDebounce(value, 2000)
    const passage = api.passage.passage.useQuery(debouncedValue)

    return (
        <div className="container min-h-screen flex flex-col mx-auto">
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className="prose mx-auto w-full flex justify-between items-center mb-2 pt-8">
                <h1 className="text-xl font-mono font-extrabold tracking-tight text-black m-0">
                    type the word
                </h1>
                <AuthShowcase />
            </nav>
            <div className="prose mx-auto w-full flex justify-start space-x-3 items-center mb-8 pt-8">
                <label htmlFor="passage" className="text-black">
                    Passage:
                </label>
                <input
                    type="text"
                    className="border-black border-2 p-1 outline-none focus-visible:outline-black"
                    value={value}
                    onChange={e => setValue(e.target.value)}
                />
            </div>

            <main className="arena relative prose mx-auto flex-grow">
                {passage.isLoading ? null : <Arena passage={passage.data!} />}
            </main>
            <footer className="prose mx-auto flex w-full justify-start items-start py-2">
                <a
                    className="no-underline flex-grow text-xs"
                    href="https://www.esv.org/"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    (ESV)
                </a>
            </footer>
        </div>
    )
}

function AuthShowcase() {
    const { data: sessionData } = useSession()

    return (
        <div className="flex flex-col  gap-4">
            <button
                className="border-2 border-black py-1 px-3 font-semibold text-black outline-none focus-visible:outline-black"
                onClick={
                    sessionData ? () => void signOut() : () => void signIn()
                }
            >
                {sessionData ? `Sign out ${sessionData.user?.name}` : 'Sign in'}
            </button>
        </div>
    )
}
