import { z } from 'zod'

export const bookSchema = z.enum([
    'genesis',
    'exodus',
    'leviticus',
    'numbers',
    'deuteronomy',
    'joshua',
    'judges',
    'ruth',
    '1_samuel',
    '2_samuel',
    '1_kings',
    '2_kings',
    '1_chronicles',
    '2_chronicles',
    'ezra',
    'nehemiah',
    'esther',
    'job',
    'psalm',
    'proverbs',
    'ecclesiastes',
    'song_of_solomon',
    'isaiah',
    'jeremiah',
    'lamentations',
    'ezekiel',
    'daniel',
    'hosea',
    'joel',
    'amos',
    'obadiah',
    'jonah',
    'micah',
    'nahum',
    'habakkuk',
    'zephaniah',
    'haggai',
    'zechariah',
    'malachi',
    'matthew',
    'mark',
    'luke',
    'john',
    'acts',
    'romans',
    '1_corinthians',
    '2_corinthians',
    'galatians',
    'ephesians',
    'philippians',
    'colossians',
    '1_thessalonians',
    '2_thessalonians',
    '1_timothy',
    '2_timothy',
    'titus',
    'philemon',
    'hebrews',
    'james',
    '1_peter',
    '2_peter',
    '1_john',
    '2_john',
    '3_john',
    'jude',
    'revelation',
])

export const Book = bookSchema.enum
export type Book = z.infer<typeof bookSchema>

